### ISSUE TITLE
Window needs: On/Pause(Buffer)/Off button

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#1]
A way of toggling the sending of text on or off - and buffering (play/pause) the text in a window. 

e.g. Something like 

!+Ctrl+F8 (Toggle).
!+Ctrl+F7 (Off)
!+Ctrl+F9 (On)

*Buffer/Pause*: 

Basically allows the person to cue the text up in a editing window - and when pressing "Play" sends the text in the window.

**Comment by willwade** [comment]
See also #4

**Comment by hosseinamin** [comment]
Buffering keys seems to be unnecessary. @willwade What do you think?

**Comment by willwade** [comment]
Yes. It is with the text: option and cli
