### ISSUE TITLE
Tweaks to QT/desktop control

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#105]
Its a bit ugly. And lacking a few things to make it more useful:

- [x] Not sure if this is possible: if resizing window can buttons resize with it?! You get a big empty space at times. I think this was originally to capture mouse movements.. 
- [x] Move Device functions into main screen. Guess device list is a dropdown? Note Joes comment below "There's no display of the device list without going to delete which feels a bit dangerous.". I wonder if we have a device list somewhere -I'm not sure right now how we could lay this out better
- [x] Put a hotkey on "Switch". LALT+N maybe?
- [ ] Deal with https://github.com/AceCentre/RelayKeys/issues/19#issuecomment-1176139162 (related to above). Maybe we need to make it a fullscreen app. Or maybe we need to try and create a way of locking focus of the app. 
- [x] Add record macro function. On record it will record key and mouse movements as a macro file. User can then save that or just replay a macro file
- [x] Wireless mode - we have a problem that the daemon is default running in wired mode. Can QT be a way of turning on/off the wireless mode on the daemon? Or do we put a switch into CLI to do this and expose it to QT maybe. 
- [x]  add https://github.com/ms7m/notify-py to CLI. add a flag of —notify bool. Default false. On true if any feedback is available on a command it will create a native notification to OS.  Particularly useful for those who control it by a third party app that can’t display messages.  
- [x]  make current device connected a label or similar. Not a button
- [x]  Make buttons bigger. But keep interface as slim as possible (Reason being people may be using large on-screen keyboards). 

any other ideas?

The main purpose of QT is to demonstrate functionality without digging into the CLI or Serial API - but some may find it useful as a tool to setup and configure - and use generally. It needs a bit of love in general

nb. I’ll keep agreed things we do in this sprint in the to do list in this note. Keep ideas and discussion coming :-)

**Comment by joedevsys** [comment]
- The layout is not great for eyegaze users.
- Current BLE device name should be a label or text box not looking like a button, preferably at the top or else at the bottom like a status bar.
- There's no display of the device list without going to delete which feels a bit dangerous.
- As some voca software can't accept text returned from a cli call they can't display the current ble device name after calling ble_cmd:switch. I have had to resort to popping up the QT app and killing it on a timer (yuk!). I'm toying with the idea of an simple alternate QT app that only displays the device name and no more as a pop-up which self-dismisses after a short time (possibly with delay time as a parameter?).

**Comment by joedevsys** [comment]
The qt has keycode tables. It should use the cli_keymap

**Comment by willwade** [comment]
Ok downside is a user has to turn off a default windows setting for full screen apps under focus assist:
<img width="655" alt="Screenshot 2022-07-07 at 22 05 11" src="https://user-images.githubusercontent.com/229352/177871300-c81680a5-4ffd-4137-83fa-f9777b985bb0.png">

But looks to be working fine. - but give it a go Joe
<img width="914" alt="Screenshot 2022-07-07 at 22 04 41" src="https://user-images.githubusercontent.com/229352/177871388-d580be6c-de1b-4960-81f1-bd58fec74fdc.png">

**Comment by willwade** [comment]
I was looking at the bow discontinued keyshare manual and it got me thinking that maybe we need an indicator light for whether it's connected or not. In its simplest state it just shows a pairing/paired status and a connected status. 

More info at http://iogear.custhelp.com/app/answers/detail/a_id/2583


Some key pics attached ![image](https://user-images.githubusercontent.com/229352/178202514-4b6561be-3a4d-44d5-a125-fe1bdf043c6e.jpeg)

![image](https://user-images.githubusercontent.com/229352/178202532-43c1caab-99f3-4f13-af2c-baaef66bd606.jpeg)

![image](https://user-images.githubusercontent.com/229352/178202547-382fe3e7-25be-4e8c-8667-4bc63874232e.jpeg)

**Comment by willwade** [comment]
Here's my latest idea. 

- 4 big tabs down left or on top. Capture , Macro, devices ,connection 
- capture : toggle switches for capture keyboard & another for capture mouse. Indicator icon for connected to board. Indicator icon for connected to a device.  Label to show what device it's connected to. Switch device button. Last sent characters field at bottom. 
- macro tab. Our macro buttons. Record , play etc 
- devices tab. List of devices. Remove selected. Remove all. Add a device. 
- relaykeys/ connection (?). Connected indicator. Reconnect. Wireless mode on / off etc. 

Couple of shoddy pics attached ![image](https://user-images.githubusercontent.com/229352/178612548-415a1991-990c-4b7b-b3c5-2ef0f4ca09ca.jpeg)

![image](https://user-images.githubusercontent.com/229352/178612557-7528bc55-b0a6-4b7f-b1c3-29ff6bff2edd.jpeg)

**Comment by joedevsys** [comment]
> I do think it could benefit from https://github.com/ms7m/notify-py for

i13 eyegaze user confirms you cannot dismiss Windows Toast popups. I haven't been able to to compile notify.py and install on the i13 yet so tested using a calender event: the popup visible above Communicator 5 but eyegaze actions restricted to communicator itself.  Windows control doesn't apply at this point while c5 is running.  

I think Toast is the the "proper" solution and good for some users, but for accessibility it MUST implement an auto-timeout AND be given alarm priority as the voca must always be set to no notifications, alarms only.  Without implementing both of these, and as Voca software can't handle CLI return info, a small pop-up QT app that just displays the device name only then self-dismisses will be needed.  

>...flag —notify on CLI that if any data returns notify os. If not just return as we currently do.
If you add toast, YES.

**Comment by willwade** [comment]
Hmm. Interesting. I assumed it would timeout. Ok. So might need to figure out an alternative. Not sure what that is. I wonder if there is a timeout time setting buried somewhere..

**Comment by joedevsys** [comment]
Sorry, I should have been clearer - if notifications have been restricted to Alarms Only (e.g. to avoid being distractions on a VOCA), then the RK notification would need to be an Alarm (scenario attribute) to get through, but it appears Alarms do not timeout and I can't see a way to add one.

So, next thing to try is Focus Assist=Priority Only and configure it to minimise unwanted stuff while permitting RK to send normal notifications. (Your link to the timeout setting noted)

**Comment by joedevsys** [comment]
I compiled the notify-py simple example which works ok. Setting  Focus Assist=Priority Only stops it popping up as you'd expect  (the event is shown in the events list ok), however it's not possible to add the test program to the Focus Assist Priority List so the popup's can't be enabled again - the app would need to register an AppUserModelId before it can be added to the priority list.  Not sure if this library supports this. https://github.com/DatGuy1/Windows-Toasts might be better but lacking documentation of this area so going to need some digging.

**Comment by willwade** [comment]
Thanks @joedevsys -I'll look into that AppUserModelId - it looks like its more of an installer thing rather than the actual notify thing (https://docs.microsoft.com/en-us/windows/win32/shell/enable-desktop-toast-with-appusermodelid). If thats the case we should be able to register cli-win.exe cli.exe with a AppUserModelId using this https://nsis.sourceforge.io/WinShell_plug-in - but still not 100% convinced. 

By the way - a large amount of commits to the workflow later - you can grab the latest installer on any commits to master on the action tab. e.g. (see at the bottom under artifacts
https://github.com/AceCentre/RelayKeys/actions/runs/2684972767 )

**Comment by joedevsys** [comment]
A few layout suggestions:
-Move Change Mode to the device menu instead of a button as it's used infrequently during setup, similar to adding/removing devices.  
-Always restart the timer (not just when not connected) so that if the dongle is disconnected later the change of status is displayed.
-Refresh the current device name on the timer as well so you no longer need a refresh button.

**Comment by willwade** [comment]
@joedevsys 

> Thanks @joedevsys -I'll look into that AppUserModelId - it looks like its more of an installer thing rather than the actual notify thing (https://docs.microsoft.com/en-us/windows/win32/shell/enable-desktop-toast-with-appusermodelid). If thats the case we should be able to register cli-win.exe cli.exe with a AppUserModelId using this https://nsis.sourceforge.io/WinShell_plug-in - but still not 100% convinced.
> 
> By the way - a large amount of commits to the workflow later - you can grab the latest installer on any commits to master on the action tab. e.g. (see at the bottom under artifacts https://github.com/AceCentre/RelayKeys/actions/runs/2684972767 )

@joedevsys I've pushed a PR thats WIP to PR #111  - see installer https://github.com/AceCentre/RelayKeys/actions/runs/2692779141 - but I cant see it working. Maybe I'm just looking at focus assist wrong (or more likely - not reading this correctly how this works)

**Comment by willwade** [comment]
massive thanks to @f1andrew for his Stellar work on this ! ✊🇺🇦🎉
