### ISSUE TITLE
ItsyBitsy nrf52840 Express dotstar led colours are wrong

### ISSUE THREAD

**Issue by joedevsys** [AceCentre/RelayKeys#119]
My ItsyBitsy nrf52840 Express dotstar led colours are wrong. When connected in wired mode it is red  not green (arduino_nRF52840.ino Line 97 updateStatusLED() comment says set to green).

ble_mode and addDevProcStarted mode colours are correct blue & yellow.

This is corrected by changing line 41  Adafruit_DotStar statusLED(1, 8, 6, DOTSTAR_BRG); to DOTSTAR_BGR

I do not know is this is any oddity for my board only or if this is a universal fix.

(Also, personally I find the dotstar is much too bright and prefer brightness values (0,0,16,0) etc for the two steady states.)

**Comment by willwade** [comment]
Yeah - I think its crazy bright on both of them. 

I'll leave @f1andrew to pick this up - but I think we could do with a brightness setting in the code for sure.
