### ISSUE TITLE
relaykeys-qt - buttons for LGUI, etc - so you can press the button - and capture any other keys

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#19]
so because the qt version cant capture windows key - im wondering about a button somewhere"Windows key" (LGUI) that would be like a toggle button - accessible by the keyboard.

**Comment by hosseinamin** [comment]
`relaykeys-qt` is capturing `LGUI` on my machine. I have to double check.

**Comment by willwade** [comment]
It does capture it - its just a pain as it also triggers all actions. We need a way of the QT app having a mode to capture all input and stop the rest of the OS reacting - I think that may be hard

**Comment by willwade** [comment]
I have no idea how we do this.. I think only way around it is to make it fullscreen. I'm closing for now. Its not essential to the project focusing on AT users
