### ISSUE TITLE
Window needs: Select OS dropdown

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#2]
I *think* we need this at least. It needs a way of choosing different keyboard layouts/and OS systems for the host machine

Warning: Need to test this but think this is the case

**Comment by willwade** [comment]
NB: Setting to be stored in config file. This may not be easy to make accessible with keyboard shortcuts.

**Comment by hosseinamin** [comment]
Implementing this issue is no longer needed.
