### ISSUE TITLE
Shift 2 = @ on Mac. Shift 2  = " on Windows. What to do?

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#20]
So - if I send LSHIFT,2 I get a @ - but actually it should be " - from a windows keyboard. What should we do about that?

**Comment by hosseinamin** [comment]
Can i see an image from these keyboards? Strange.

Are you saying it should be double quote?

**Comment by willwade** [comment]
Mac:
![IMG_9226](https://user-images.githubusercontent.com/229352/54274743-c719d480-4580-11e9-8b46-3df3a2873f38.JPG)
![IMG_1292](https://user-images.githubusercontent.com/229352/54274745-c7b26b00-4580-11e9-9703-30a0ea9cfbe2.JPG)

Windows: 
![IMG_1391](https://user-images.githubusercontent.com/229352/54274752-d13bd300-4580-11e9-9959-fef692d108ac.JPG)
![IMG_4295](https://user-images.githubusercontent.com/229352/54274753-d1d46980-4580-11e9-9da1-0e271352e94e.JPG)

This may be of use: https://github.com/Mottie/Keyboard/tree/master/layouts 

(they've taken it largely from http://ascii-table.com/keyboards.php)

**Comment by hosseinamin** [comment]
@willwade Thanks

**Comment by hosseinamin** [comment]
What will shift + quote do, on windows?

**Comment by hosseinamin** [comment]
I mean `@` sign, on the windows layout version.

**Comment by willwade** [comment]
So I send try and send the shift,backtick key (@) - and I get  ~ (tilde).
If I send Shift 2 - I get @ (which is the Mac layout).

**Comment by hosseinamin** [comment]
> So I send try and send the shift,backtick key (@) - and I get ~ (tilde).
> If I send Shift 2 (quote) - I get @ (which is the Mac layout).

I want to know what will show up in `relaykeys-qt` when you press with or without shift these keys (`@` and `~`) on the black keyboard in that image.

**Comment by hosseinamin** [comment]
@willwade I figured out what the issue is.
The keyboard you have in your windows machine has UK keyboard layout. Still in your windows machine layout has set right. But on the host machine (say iOS) US keyboard layout is selected. I think if you change the layout on iOS it will get fixed.

Also `@` sign was in `relaykeys-qt` which I did add in my earlier commits.

**Comment by joedevsys** [comment]
see #94 nonchars_key_map needs to match your operating system's keyboard localisation
