### ISSUE TITLE
CLI to support multiple keyevents

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#23]
To Save a lot of lines - I think we need a way of the CLI dealing with a string of keyevent: - just not sure best way to do this.

**Comment by hosseinamin** [comment]
Queuing keyevents in series is already supported by adding multiple commands to a single execution arguments. I'm not sure how else is best to do it. It looks pretty good. Maybe using an alias to `keyevent:` will do it. `ke:` or `k:`

**Comment by willwade** [comment]
sorry - mind explaining how that works? 

is it something like : 
``keyevent:A,LSHIFT,0 keyevent:B,LSHIFT,1``

?

**Comment by hosseinamin** [comment]
Yes. You can add more than one.

**Comment by willwade** [comment]
ah ok. then done :)
