### ISSUE TITLE
RPC Server  - option to respond with last n characters sent.. 

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#25]
**Is your feature request related to a problem? Please describe.**
A client who is trying relayKeys likes it - but is getting tired switching their view from one machine to another. 

**Describe the solution you'd like**
He has asked whether we could display the last n characters sent.. I imagine we could build this into the qt version - but really its for the RPC protocol. So something like type:hello --viewlast 30 

When then sending a command the rpc server would respond with OK - but also the string of chars sent. 

**Describe alternatives you've considered**
Cant think of anything

**Comment by hosseinamin** [comment]
We can interpret given keystrokes as typing. Then with cli or qt show them.
