### ISSUE TITLE
Support consumer media keys. 

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#26]
This is needed for iOS etc control. See AT+BLEHIDCONTROLKEY at https://learn.adafruit.com/introducing-adafruit-ble-bluetooth-low-energy-friend/ble-services and consumerKey here https://learn.adafruit.com/introducing-the-adafruit-nrf52840-feather/blehidadafruit

**Comment by RoganDawes** [comment]
Still trying to convince you :-)

VNC would make this simple, as you just need to detect the local key event, and make sure that there is a keyboard mapping for it on the bluetooth side.

**Comment by willwade** [comment]
Initially done with https://github.com/AceCentre/RelayKeys/pull/129 - VOLUP VOLDOWN or MUTE. adding a whole new AT command avoided but if this needs it we can review.
