### ISSUE TITLE
Mouse control

### ISSUE THREAD

**Issue by willwade** [AceCentre/RelayKeys#3]
Needs some thought this..

My suggestion:
We provide two Forms of mouse control:

1. Mouse free-flow window

The window acts like a glidepad. You move the mouse towards the top left - it moves the mouse on the second screen in the same way towards the top left of the screen.

2. Mouse control with buttons

A window is provided with buttons like so (credit to Dynavox for this.. I've basically pinched the idea but loads of people have replicated this in other ways):

<img width="608" alt="screenshot 2019-01-21 at 01 56 42" src="https://user-images.githubusercontent.com/229352/51448638-da968500-1d1f-11e9-86de-32cfce46bf02.png">

Clicking on these buttons (or activating the relevant keyboard shorcut for each button) - activates the mouse. Note Continuous = Continually moves until user presses an Incremental or action button. Incremental  = Moves the cursor in small amounts (5 px at a time for example).

**Comment by willwade** [comment]
NB: We can now do this over the CLI & Create the GUI in our AAC App of choice. Key thing is making the AT Commands work for mouse control https://learn.adafruit.com/introducing-bluefruit-ez-key-diy-bluetooth-hid-keyboard/sending-keys-via-serial#raw-hid-mouse-reports-8-11

**Comment by hosseinamin** [comment]
Here are the cli commands.

```
relaykeys-cli mousemove:5,5 # 5 right and 5 down
relaykeys-cli mousebutton:l,click # left button click
relaykeys-cli mousebutton:r,doubleclick # right button click
```
