### ISSUE TITLE
Windows Service cannot be stopped or restarted

### ISSUE THREAD

**Issue by joedevsys** [AceCentre/RelayKeys#71]
On Windows the relaykeys daemon service cannot be stopped or restarted.

**To Reproduce**
Run services.msc as administrator. Select the running relaykeys daemon service. Click on either "restart" or "stop" and the dialog hangs for a long period and then fails, reporting error 1053.  If the daemon is running it continues to function sending keys from the cli to the remote computer and does not terminate. A crashed daemon cannot be restarted this way (you need to terminate the process from task manager first).

Also, running relaykeysd-service-restart.bat as administrator does fails after a long pause.

**Expected behavior**
Clicking stop should end the service and stop relaying keys until start is clicked. Clicking restart should restart a failed daemon.

**System info**
Windows 10. 
Bluefruit LE Friend.

**Comment by willwade** [comment]
Think fixed some of this - but note you do need to run services as admin to stop it. Its an elevated process

**Comment by willwade** [comment]
Yep - this does look fixed. Run services as admin - and then stop it. Then install the new build. Does look like its working now!
