### ISSUE TITLE
CLI Paste command - occasional delayed keyup

### ISSUE THREAD

**Issue by joedevsys** [AceCentre/RelayKeys#80]
When sending large text strings using the CLI paste command occasionally one of the characters is repeated 15-20 times. 

Tested using the #76 pre-compiled installer with a Bluefruit BLE Friend connected to an Android phone. Also see non an old Window tablet. I copied approx 3kB text into the clipboard and sent it using the CLI paste command. All the text arrived on the target and the only problem was some additional repeating characters. Over the 3kB block this would occur around 2-3 times.

Example:
The source text might contain this "Lorem ipsum dolor sit amet, consectetur adipiscing elit." as part of a longer string. The target would end up looking like this: "Lorem ipsum dolor sit amet, consectetur adddddddddddddddddddddddddddddipiscing elit,"

Presumably this is caused by a delay receiving a key up command and autorepeat causing the repeats until the key up command finally arrives. It appears the key does arrive as the offending character does stop repeating. Perhaps this is a buffering issue?

**Comment by joedevsys** [comment]
Now tested using 1.7 pre-compiled installer: This produces both repeating characters AND occasional sections with missing characters also. I haven't examined the code differences but what's interesting is the different results between the two software versions. If it's a timing/buffering issue will be interesting to see how controlling bandwidth affects this. The missing characters occur in groups over a period of a few seconds interspersed with longer periods where typing is accurate.

**Comment by joedevsys** [comment]
With BLE Friend, dropping the baudrate to 38400 this problem goes away. The overall throughput subjectively seems similar.

**Comment by joedevsys** [comment]
Nope, I'm still seeing a few of these. 

The problem also occurs with the keypress command: sending a series of keypresses for various characters and every so often one of them goes into autorepeat (i13, relaykeys 1.7, Bluefruit Friend, 38400 baud, Android phone).

**Comment by joedevsys** [comment]
v1.8 pre-compiled installer with BLEFriend:  
I now think there have been multiple causes to these problems some of which have been improved in the latest version and others that are bandwidth/baudrate or flow control issues which require more testing. In the latest version I have seen a few errors with pasting large texts and will report back after more tests.

I have found an  **additional** cause of autorepeats when scripting pairs of press/release keyevents (e.g. keyevent:A,none,1;  keyevent:A,none,0). If the scripting engine does not wait for a command to complete before going onto the next line of the script then it's necessary to put a small delay between the calls (200mS seems to work but this is not determinate). 

For example, Communicator 5 has no blocking run command to call external programs so the following script sometimes causes autorepeats: 
run  "relaykeys-cli.exe keyevent:A,none,1 
run  "relaykeys-cli.exe keyevent:A,none,0

I think Windows can sometimes take so long to launch the .exe that the second call goes ahead before the first is complete. This can be solved by using a blocking call if it's available (there isn't one in Communicator 5) or putting a delay command between the two calls, e.g.
run  "relaykeys-cli.exe keyevent:A,none,1 
delay 0.20
run  "relaykeys-cli.exe keyevent:A,none,0

This fail mode can also be demonstrated in AutoHotKeys using the RUN command, whereas using the RUNWAIT blockinh command is reliable. Clearly this particular problem lies with the limitations of the calling applications and not with RelayKeys itself.

**Comment by willwade** [comment]
Just to add to this - its a right pain. The AAC software should really be providing a better SDK/Method to call an external application. Its pretty rubbish.. Smartbox do note that if the window of the calling app isn't set to background it will actually be faster. But you will end up with a big black square of the app as it loads when you do this.. I couldn't figure out a workaround

**Comment by joedevsys** [comment]
TBH for most practical purposes for a single character press-release it would be better to use keypress. It's more likely to bite someone trying to send a chord.

**Comment by willwade** [comment]
I doubt this will do much - try the application called ``relaykeys-cli-win.exe`` in place of relaykeys-cli.exe. Its exactly the same but windowed. The story from Smartbox (but I feel relevant to TD as well) is this should be faster and application calls dont wait (but looks more ugly)
