### ISSUE TITLE
mousebutton command: implement button press & release behaviours

### ISSUE THREAD

**Issue by joedevsys** [AceCentre/RelayKeys#88]
Mousebutton command implements click and doubleclick behaviours. Also need separate button press and button release (or down and up)  behaviours so that drag and swipe operations can be performed like this:
mousebutton:L,press
mousemove:0,10
mousebutton:L,release

See also #21 how would drag work?

**Comment by willwade** [comment]
Ok. 

With relaykeys-cli pressing and holding mouse button works with:
python relaykeys-cli.py mousebutton:L,press
Or:
python relaykeys-cli.py mousebutton:L (like @joedevsys suggested in https://github.com/AceCentre/RelayKeys/issues/21)

Releasing button can be made like this:
python relaykeys-cli.py mousebutton:0

Bluefruit library has only general function for releasing mousebuttons: https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/src/services/BLEHidAdafruit.h#L102

so we may get stuck expanding this further. Does this work for you though Joe?

**Comment by joedevsys** [comment]
That seems to work. I can drag e.g. select an area of text now.  

N.B. Using click, doubleclick or rightclick will all release a previously pressed button. Rightclick will cancel L press!
