### ISSUE TITLE
Change default pin for USER_SW to D4?

### ISSUE THREAD

**Issue by joedevsys** [AceCentre/RelayKeys#91]
The Adafruit Itsybitsy nrf52840 Express has an uncommitted switch onboard wired to D4.  Optionally change file arduino_nRF52840.ino 
to #define USER_SW 4  and then you don't have to wire an additional switch.

**Comment by willwade** [comment]
Aha - I wanted to provide you with a standard feather but couldnt get my hands on one. My bodge is to alter the line dependent on board.

**Comment by willwade** [comment]
slightly better bodge. This should, in theory, stop you needing to hard code and change the PIN number..
